- name: Configure mysql server
  hosts: mysql
  become: yes
  tasks: 
  #installing required libraries 
  - name: Install MySQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL 
  #installing mysql
  - name: install my sql server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  #enabling and starting the service
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  #setting the root password and seeing if we can connect to mysql using it 
  - name: connect to the mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.learningmaniac.fun